// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfabttvmqbitomghdiel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmYWJ0dHZtcWJpdG9tZ2hkaWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjc2MjksImV4cCI6MjA2Njk0MzYyOX0.VpGfXHcq0glB6ybfFxmLI7u0nF9Qzh5XVEw0Q8-5mBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});